spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/nvg8db}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate.default_batch_fetch_size: 50

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  devMode: ${APP_DEV_MODE:true}




  cookie:
    name: token
    domain: ${APP_COOKIE_DOMAIN:}          # DEV: leer lassen!
    secure: ${APP_COOKIE_SECURE:false}     # DEV: false
    sameSite: ${APP_COOKIE_SAMESITE:Lax}   # DEV: Lax
    maxAgeSeconds: ${APP_COOKIE_MAXAGE:3600}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,mappings
  endpoint:
    mappings:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.web.FilterChainProxy: INFO
    org.thomcgn.backend.config.JwtAuthFilter: INFO
    org.thomcgn.backend.config.SecurityConfig: INFO
